sudo: false
language: generic
dist: trusty

env:
  - CMAKE_TARGET=Debug COVERAGE=ON
# - CMAKE_TARGET=Debug COVERAGE=OFF # XXX: see https://github.com/travis-ci/travis-ci/issues/9033
  - CMAKE_TARGET=Release COVERAGE=OFF

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libblas-dev
      - binutils-gold

script:
  - mkdir build
  - cd build
  - cmake -DJULES_BUILD_TEST=ON -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_BUILD_TYPE=$CMAKE_TARGET -DJULES_TEST_COVERAGE=$COVERAGE ..
  - make -j2 VERBOSE=1
  - ctest -j2 -VV

after_success:
  - if test "$COVERAGE" == "ON"; then bash <(curl -s https://codecov.io/bash) -x $(which gcov-7); fi
