sudo: false
language: generic
dist: trusty

env:
  - CMAKE_TARGET=Debug COVERAGE=ON
  - CMAKE_TARGET=Debug COVERAGE=OFF
  - CMAKE_TARGET=Release COVERAGE=OFF

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libblas-dev
      - binutils-gold

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_TARGET -DJULES_TEST_COVERAGE=$COVERAGE ..
  - make
  - test/jules_test_suite

after_success:
  - if test "$COVERAGE" == "ON"; then bash <(curl -s https://codecov.io/bash) -x $(which gcov-7); fi
